<?xml version="1.0"?>
<package format="3">
  <name>velocity_scaling_iso15066</name>
  <version>0.0.0</version>
  <description>The velocity_scaling_iso15066 package</description>

  <maintainer email="jacobi@todo.todo">jacobi</maintainer>

  <license>TODO</license>

  <license>BSD-3-Clause</license>

  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION != 2">cmake</buildtool_depend>
  <build_depend>rdyn_core</build_depend>
  <build_export_depend>rdyn_core</build_export_depend>
  <exec_depend>rdyn_core</exec_depend>
  
  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <!-- Other tools can request additional information be placed here -->

  </export>
</package>
